projetoRails/cicmonit/config/routes.rb
Rails.application.routes.draw do

  resources :candidatos
  devise_for :users
  get 'sessions/new'

  get 'info_page/index'

  get 'docentes/index'

  get 'docentes/listar'

  get 'docentes/listarPorIRA'

  get 'docentes/listarTurmas'

  get 'docentes/show'

  get 'alunos/insere'

  get 'alunos/listar'

  resources :alunos

  resources :docentes
  devise_for :professors
  resources :professors

   unauthenticated do
       root :to =>"alunos#FrontPage", as: :unauthenticated_root
   end

  get 'disciplinas/showCampus'

  get 'disciplinas/showDepartamentos'

  get 'disciplinas/showDisciplinas'

  get 'disciplinas/showTurmas'

  get 'disciplinas/showTurma'

  get 'disciplinas/showHorarios'

  get 'disciplinas/showProfessores'

    get 'disciplinas/showCandidatos'

	resources:disciplina
  get 'configuracoes/index'
  get 'configuracoes/rungetdb'
  get 'configuracoes/runalocabolsas'
  get 'configuracoes/setbolsas'

  root 'alunos#FrontPage'

end

projetoRails/cicmonit/app/models/aluno.rb
class Aluno < ActiveRecord::Base
  validates :nome, length: {minimum:5, maximum: 255 }
  validates :nome, presence: true
  validates :matricula, presence: true
  validates :IRA, presence: true
  validates :semestre, inclusion: { in: 1..10 }
  validates :semestre, presence: true
  validates :user_id, presence: true
  validates :matricula, uniqueness: true


  has_many :candidatos

  belongs_to :user

end

projetoRails/cicmonit/app/controllers/alunos_controller.rb
class AlunosController < ApplicationController
  before_action :set_aluno, only: [:show, :edit, :update, :destroy]
  #before_action :authenticate_user! # nao precisa ir direto para a autenticacao antes de entrar
  # na parte de alunos pq as rotas do routes.rb ja direcionam para a pagina principal (a partir da qual
  # sera feito o login) quando o usuario nao esta autenticado


  # GET /alunos
  # GET /alunos.json
  def index
    # @alunos = Aluno.all
    @alunos = current_user.alunos
  end

  def listar
    @aluno = Aluno.where(user_id: current_user.id)
  end

  # GET /alunos/1
  # GET /alunos/1.json

  def show
  	render
  end

  # GET /alunos/new
  def new
    @aluno = Aluno.new
  end

  def insere
    @use = User.find(current_user.id)

    matricula = @use.email[0..8]

    system "python python.py #{matricula} #{$pass} #{@use.id}"

  end

  # GET /alunos/1/edit
  def edit
  end

  # POST /alunos
  # POST /alunos.json
  def create
    @aluno = Aluno.new(aluno_params)
    @aluno.user_id = current_user.id
    respond_to do |format|
      if @aluno.save
        format.html { redirect_to @aluno, notice: "Sucesso no cadastro do dicente #{@aluno.nome}." }
        format.json { render :show, status: :created, location: @aluno }
      else
        format.html { render :new }
        format.json { render json: @aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alunos/1
  # PATCH/PUT /alunos/1.json
  def update
    respond_to do |format|
      if @aluno.update(aluno_params)
        format.html { redirect_to @aluno, notice: "Sucesso no atualização do dicente #{@aluno.nome}."}
        format.json { render :show, status: :ok, location: @aluno }
      else
        format.html { render :edit }
        format.json { render json: @aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alunos/1
  # DELETE /alunos/1.json
  def destroy
    @aluno.destroy
    respond_to do |format|
      format.html { redirect_to alunos_url, notice: "Sucesso na exclusão do dicente #{@aluno.nome}." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aluno
      # @aluno = Aluno.find(params[:id])
      @aluno = current_user.alunos.find(params[:id])

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def aluno_params
      params.require(:aluno).permit(:nome, :matricula, :semestre, :IRA)
    end
end

projetoRails/cicmonit/app/helpers/alunos_helper.rb
module AlunosHelper
  def formata_matricula(n_matricula)
    mat_formatada = ""
    mat_formatada << n_matricula[0..1]
    mat_formatada << "/"
    mat_formatada << n_matricula[2..8]
  end

  def formata_semestre(n_semestre)
    sem_formatado = "#{n_semestre}"
    sem_formatado << "º"
  end

end

projetoRails/cicmonit/app/views/alunos/FrontPage.html.erb
<h1 class="Titulo"> Bem-vindo à Monitoria </h1>

<div class="front-links">

</body>

projetoRails/cicmonit/app/views/alunos/_form.html.erb
<%= form_for(@aluno) do |f| %>
  <% if @aluno.errors.any? %>
    <div id="errorExplanation">
      <h2><%= pluralize(@aluno.errors.count, "erro(s)") %> encontrado(s):</h2>
      <ul>
      <% @aluno.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<body>
  <div class="login">
    <div class="container">
      <div class="form">
  <div class="field">
    <font><%= f.label :nome %><br></font>
    <%= f.text_field :nome, :size=>"50", placeholder: "Digite seu nome", :maxlength=>"50"   %>
  </div>
  <div class="field">
    <font><%= f.label :matrícula %><br></font>

    <%= f.text_field :matricula, :size=>"11", placeholder: "Digite sua matrícula", :maxlength=>"9"  %>

  </div>

  <div class="field">
    <font><%= f.label :semestre %><br></font>
    <%= f.number_field :semestre, placeholder: "Digite seu semestre", min:1, max:10 %>
  </div>
  <div class="field">
    <font><%= f.label :IRA, "IRA" %><br></font>
    <%= f.number_field :IRA, placeholder:"5.00", min: 0.00, max: 5.00, :step => 0.0001, :maxlength=>"3" %>
  </div>

  <div class="actions">
    <%= f.submit "Criar novo aluno", class: "btn-submit"%>
  </div>
  </div>
  </div>
  </div>

  </body>
<%end%>

projetoRails/cicmonit/app/views/alunos/edit.html.erb
<h1>Editar Dicente</h1>

<%= render 'form' %>

<%= link_to image_tag("show.png"), @aluno %> |
<%= link_to image_tag("back.png"), alunos_path %>

projetoRails/cicmonit/app/views/alunos/index.html.erb
<h1>Dicente</h1>
<head>
</head>

<table>
  <thead>
    <tr bgcolor="6B9A8C">
      <th>Nome</th>
      <th>Matrícula</th>
      <th>Semestre</th>
      <th>IRA</th>

    </tr>
  </thead>

  <tbody>
    <% @alunos.each do |aluno| %>
      <tr>
        <td><%= aluno.nome %></td>
        <td><%= formata_matricula(aluno.matricula) %></td>
        <td><%= formata_semestre(aluno.semestre) %></td>
        <td><%= aluno.IRA %></td>
        <!-- <td><%= link_to image_tag("show.png"), aluno %></td> -->
        <!-- <td><%= link_to image_tag("edit.png"), edit_aluno_path(aluno) %></td> -->
        <!-- <td><%= link_to image_tag("delete.png"), aluno, method: :delete, data: { confirm: "Você tem certeza que deseja excluir o dicente #{aluno.nome}?" } %></td> -->
	<!-- <td><%=link_to 'Campus',disciplinas_showCampus_path %> </td> -->
	</tr>
    <% end %>
  </tbody>
</table>
</body>
<br>

<% se = Aluno.where(user_id: current_user.id).count %>

<% if se == 0 %>
<%=link_to image_tag("new.png"), :controller => "alunos", :action => "insere"%>
<% end %>

projetoRails/cicmonit/app/views/alunos/listar.html.erb
<h1>Lista de candidatura</h1>
<table>
<tr bgcolor="6B9A8C">
  <th >Aluno</th>
  <th>Avaliação</th>
  <th>Disciplina</th>
  <th>Menção na Disciplina</th>
  <th>Turma</th>

</tr>
<% @aluno.each do|aluno| %>

    <% candidato = aluno.candidatos %>
    <% candidato.each do|candidato| %>

        <% turma = candidato.turmas %>
        <% turma.each do|turma| %>

        <% disciplina = Disciplina.find(turma.disciplina_id)%>

                <tr>
                  <td><%= aluno.nome %></td>
                  <% if candidato.avaliacao == 0%>
                  <td><%= "INDEFERIDA"%></td>
                  <% elsif candidato.avaliacao == 1%>
                  <td><%= "VOLUNTARIO"%></td>
                  <% elsif candidato.avaliacao == 2%>
                  <td><%= "REMUNERADO"%></td>
                  <%else%>
                  <td><%= "AMBAS"%></td>
                  <%end%>
                  <td><%= disciplina.nome %></td>
                  <td><%= candidato.mencao %></td>
                  <td><%= turma.nome %></td>

                  <td><%= link_to image_tag("delete.png"), candidato, method: :delete, data: { confirm: "Você tem certeza que deseja excluir sua candidatura na turma #{turma.nome} de #{disciplina.nome}" } %></td>

                </tr>

        <% end %>
    <% end %>
<% end %>
</table>
</body>

projetoRails/cicmonit/app/views/alunos/new.html.erb
<h1>Novo Dicente</h1>

<%= render 'form' %>

<b><strong><%= link_to image_tag("back.png"), alunos_path %></b></strong>

projetoRails/cicmonit/app/views/alunos/show.html.erb
<h1>Dicente</h1>
<body>
<p>
  <strong>Nome:</strong>
  <%= @aluno.nome %>
</p>

<p>
  <strong>Matrícula:</strong>
  <%= @aluno.matricula %>
</p>

<p>
<strong>Semestre:</strong>
<%= @aluno.semestre %>
</p>

<p>
  <strong>IRA:</strong>
  <%= @aluno.IRA %>
</p>
</body>

<!-- <%= link_to image_tag("edit.png"), edit_aluno_path(@aluno) %> | -->
<%= link_to image_tag("back.png"), alunos_path %>
<!-- <%= link_to 'Campus',disciplinas_showCampus_path %> -->