projetoRails/cicmonit/config/routes.rb
Rails.application.routes.draw do

  resources :candidatos
  devise_for :users
  get 'sessions/new'

  get 'info_page/index'

  get 'docentes/index'

  get 'docentes/listar'

  get 'docentes/listarPorIRA'

  get 'docentes/listarTurmas'

  get 'docentes/show'

  get 'alunos/insere'

  get 'alunos/listar'

  resources :alunos

  resources :docentes
  devise_for :professors
  resources :professors

   unauthenticated do
       root :to =>"alunos#FrontPage", as: :unauthenticated_root
   end

  get 'disciplinas/showCampus'

  get 'disciplinas/showDepartamentos'

  get 'disciplinas/showDisciplinas'

  get 'disciplinas/showTurmas'

  get 'disciplinas/showTurma'

  get 'disciplinas/showHorarios'

  get 'disciplinas/showProfessores'

    get 'disciplinas/showCandidatos'

	resources:disciplina
  get 'configuracoes/index'
  get 'configuracoes/rungetdb'
  get 'configuracoes/runalocabolsas'
  get 'configuracoes/setbolsas'

  root 'alunos#FrontPage'

end

projetoRails/cicmonit/app/models/docente.rb
class Docente < ActiveRecord::Base
  validates :nome, length: {maximum: 255 }
  validates :nome, presence: true

  belongs_to :user
  has_and_belongs_to_many :turmas
end

projetoRails/cicmonit/app/controllers/docentes_controller.rb
class DocentesController < ApplicationController
  before_action :set_docente, only: [:show, :edit, :update, :destroy]
  #before_action :authenticate_user! # nao precisa ir direto para a autenticacao antes de entrar
  # na parte de docentes pq as rotas do routes.rb ja direcionam para a pagina principal (a partir da qual
  # sera feito o login) quando o usuario nao esta autenticado


  # GET /docentes
  # GET /docentes.json
  def index
    # @docentes = Docente.all
    @docentes = current_user.docentes
  end

  def listarTurmas
    @docentes = Docente.where(user_id: current_user.id)
    #@docentes = current_user.docentes
  end

  def listar
    @turma = Turma.find(params[:id])
    #@docentes = current_user.docentes
  end

  def listarPorIRA
    @turma = Turma.find(params[:id])
    #@docentes = current_user.docentes
  end
  # GET /docentes/1
  # GET /docentes/1.json

  def show
  	render
  end

  # GET /docentes/new
  def new
    @docente = Docente.new
  end

  # GET /docentes/1/edit
  def edit
  end

  # POST /docentes
  # POST /docentes.json
  def create
    @docente = Docente.where("nome = ?", docente_params["nome"])
    User.find(current_user.id).docentes << @docente
    respond_to do |format|
        format.html { redirect_to :edit => 'localhost:3000/docentes'}
        format.json { render :show, status: :created, location: @docente }
    end
  end

  # PATCH/PUT /docentes/1
  # PATCH/PUT /docentes/1.json
  def update
    respond_to do |format|
      if @docente.update(docente_params)
        format.html { redirect_to @docente, notice: "Sucesso no atualização do docente #{@docente.nome}."}
        format.json { render :show, status: :ok, location: @docente }
      else
        format.html { render :edit }
        format.json { render json: @docente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /docentes/1
  # DELETE /docentes/1.json
  def destroy
    @docente.destroy
    respond_to do |format|
      format.html { redirect_to docentes_url, notice: "Sucesso na exclusão do docente #{@docente.nome}." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_docente
      # @docente = Docente.find(params[:id])
      @docente = current_user.docentes.find(params[:id])

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def docente_params
      params.require(:docente).permit(:nome)
    end
end

projetoRails/cicmonit/app/helpers/docentes_helper.rb
module DocentesHelper
end

projetoRails/cicmonit/app/views/docentes/FrontPage.html.erb
<h1 class="Titulo"> Bem-vindo a Monitoria </h1>

<div class="front-links">

</body>

projetoRails/cicmonit/app/views/docentes/_form.html.erb
<%= form_for(@docente) do |f| %>
  <% if @docente.errors.any? %>
    <div id="errorExplanation">
      <h2><%= pluralize(@docente.errors.count, "erro(s)") %> encontrado(s):</h2>
      <ul>
      <% @docente.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<body>
  <div class="login">
    <div class="container">
      <div class="form">
  <div class="field">
    <font color="red"><%= f.label :nome %><br></font>
    <%= f.text_field :nome, :size=>"50", placeholder: "Digite seu nome", :maxlength=>"50"   %>
  </div>

  <div class="actions">
    <%= f.submit "Criar novo docente", class: "btn-submit"%>
  </div>
  </div>
  </div>
  </div>

  </body>
<%end%>

projetoRails/cicmonit/app/views/docentes/edit.html.erb
<h1>Editar Dicente</h1>

<%= render 'form' %>

<%= link_to image_tag("show.png"), @docente %> |
<%= link_to image_tag("back.png"), docentes_path %>

projetoRails/cicmonit/app/views/docentes/index.html.erb
<h1>Dicente</h1>
<head>
</head>

<table>
  <thead>
    <tr bgcolor="6B9A8C">
      <th>Nome</th>

    </tr>
  </thead>

  <tbody>
    <% @docentes.each do |docente| %>
      <tr>
        <td><%= docente.nome %></td>
	     </tr>
    <% end %>
  </tbody>
</table>
</body>
<br>

<% se = Docente.where(user_id: current_user.id).count %>

<% if se == 0 %>
<%= link_to image_tag("new.png"), new_docente_path %>
<% end %>
<table>
<!-- <tr>
  <th align="center">Aluno</th>
  <th align="center">Avaliação</th>
  <th align="center">Disciplina</th>
  <th align="center">Menção na Disciplina</th>
  <th align="center">Turma</th>

</tr> -->

<!%@aluno =  Aluno.all%>
<!% @aluno.each do|aluno| %>

    <!% candidato = aluno.candidatos %>
    <!% candidato.each do|candidato| %>

        <!% turma = candidato.turmas %>
        <!% turma.each do|turma| %>

        <!% disciplina = Disciplina.find(turma.disciplina_id)%>

                <!tr>
                  <!td align="center"><!%=link_to aluno.nome, edit_candidato_path(candidato) %><!/td>
                  <!% if candidato.avaliacao == 0%>
                  <!td align="center"><!%= "INDEFERIDA"%><!/td>
                  <!% elsif candidato.avaliacao == 1%>
                  <!td align="center"><!%= "VOLUNTARIO"%><!/td>
                  <!% elsif candidato.avaliacao == 2%>
                  <!td align="center"><!%= "REMUNERADO"%><!/td>
                  <!%else%>
                  <!td align="center"><!%= "AMBAS"%><!/td>
                  <!%end%>
                  <!td align="center"><!%= disciplina.nome %><!/td>
                  <!td align="center"><!%= candidato.mencao %><!/td>
                  <!td align="center"><!%= turma.nome %><!/td>

                  <!td><!%= link_to image_tag("delete.png"), candidato, method: :delete, data: { confirm: "Você tem certeza que deseja excluir sua candidatura na turma #{turma.nome} de #{disciplina.nome}" } %><!/td>

                <!/tr>

        <!% end %>
    <!% end %>
<!% end %>
</table>
</body>

projetoRails/cicmonit/app/views/docentes/listar.html.erb
<h1>Lista de candidatura</h1>
<table>
<tr>
  <th align="center">Aluno</th>
  <th align="center">Avaliação</th>
  <th align="center">Disciplina</th>
  <th align="center">Menção na Disciplina</th>
  <th align="center">Turma</th>

</tr>

<% candidato = @turma.candidatos %>
<% candidato.each do|candidato| %>
<% aluno = Aluno.find(candidato.aluno_id)%>
<% disciplina = Disciplina.find(@turma.disciplina_id)%>

      <tr>
        <td align="center"><%=link_to aluno.nome, edit_candidato_path(candidato) %></td>
        <% if candidato.avaliacao == 0%>
        <td align="center"><%= "INDEFERIDA"%></td>
        <% elsif candidato.avaliacao == 1%>
        <td align="center"><%= "VOLUNTARIO"%></td>
        <% elsif candidato.avaliacao == 2%>
        <td align="center"><%= "REMUNERADO"%></td>
        <%else%>
        <td align="center"><%= "AMBAS"%></td>
        <%end%>
        <td align="center"><%= disciplina.nome %></td>
        <td align="center"><%= candidato.mencao %></td>
        <td align="center"><%= @turma.nome %></td>

      </tr>
<% end %>

</table>
</body>

projetoRails/cicmonit/app/views/docentes/listarPorIRA.html.erb
<h1>Lista de candidatura</h1>
<table>
<tr>
  <th> Aluno </th>
  <th> Avaliação </th>
  <th> Disciplina </th>
  <th> Menção na Disciplina </th>
  <th> IRA </th>
  <th> Turma </th>

</tr>

<% candidato = @turma.candidatos %>
<% candidato.joins(:aluno).merge(Aluno.order(ira: :desc)).order(mencao: :desc).each do|candidato| %>
<% aluno = Aluno.find(candidato.aluno_id)%>
<% disciplina = Disciplina.find(@turma.disciplina_id)%>

      <tr>
        <td><%=link_to aluno.nome, edit_candidato_path(candidato) %></td>
        <% if candidato.avaliacao == 0%>
        <td class="indeferido"><%="INDEFERIDA"%></td>
        <% elsif candidato.avaliacao == 1%>
        <td class="voluntario"><%="VOLUNTARIO"%></td>
        <% elsif candidato.avaliacao == 2%>
        <td class="remurado"><%="REMUNERADO"%></td>
        <%else%>
        <td class="ambas"><%="AMBAS"%></td>
        <%end%>
        <td><%= disciplina.nome %></td>
        <td><%= candidato.mencao %></td>
        <td><%= aluno.IRA %></td>
        <td><%= @turma.nome %></td>

      </tr>
<% end %>

</table>
</body>

<br/><%=link_to "Listar por menção/IRA", controller: "docentes", action: "listar", id: @turma.id%></li>

projetoRails/cicmonit/app/views/docentes/listarTurmas.html.erb
<h1>Lista de turmas</h1>

<% @docente = Docente.where(user_id: current_user.id) %>
<table>
  <tr bgcolor="6B9A8C">
    <th>Turmas do docente</th>

  </tr>
<% @docente.each do|docente| %>
    <% turma = docente.turmas %>
    <% turma.each do|turma| %>
<tr>
    <th><%= Disciplina.find(turma.disciplina_id).nome %>  <%= link_to 'Turma: ', controller: "docentes", action: 'listar', id: turma.id %><%= link_to turma.nome, controller: "docentes", action: 'listar', id: turma.id %></th>
</tr>
    <% end %>
<% end %>

</table>
</body>

projetoRails/cicmonit/app/views/docentes/new.html.erb
<h1>Novo Dicente</h1>

<%= render 'form' %>

<b><strong><%= link_to image_tag("back.png"), docentes_path %></b></strong>

projetoRails/cicmonit/app/views/docentes/show.html.erb
<h1>Discente</h1>
<body>
<p>
  <strong>Nome:</strong>
  <%= @docente.nome %>
</p>

</body>

<!-- <%= link_to image_tag("edit.png"), edit_docente_path(@docente) %> | -->
<%= link_to image_tag("back.png"), docentes_path %>
<!-- <%= link_to 'Campus',disciplinas_showCampus_path %> -->