projetoRails/cicmonit/config/routes.rb
Rails.application.routes.draw do

  resources :candidatos
  devise_for :users
  get 'sessions/new'

  get 'info_page/index'

  get 'docentes/index'

  get 'docentes/listar'

  get 'docentes/listarPorIRA'

  get 'docentes/listarTurmas'

  get 'docentes/show'

  get 'alunos/insere'

  get 'alunos/listar'

  resources :alunos

  resources :docentes
  devise_for :professors
  resources :professors

   unauthenticated do
       root :to =>"alunos#FrontPage", as: :unauthenticated_root
   end

  get 'disciplinas/showCampus'

  get 'disciplinas/showDepartamentos'

  get 'disciplinas/showDisciplinas'

  get 'disciplinas/showTurmas'

  get 'disciplinas/showTurma'

  get 'disciplinas/showHorarios'

  get 'disciplinas/showProfessores'

    get 'disciplinas/showCandidatos'

	resources:disciplina
  get 'configuracoes/index'
  get 'configuracoes/rungetdb'
  get 'configuracoes/runalocabolsas'
  get 'configuracoes/setbolsas'

  root 'alunos#FrontPage'

end

projetoRails/cicmonit/app/models/professor.rb
class Professor < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  ##devise :database_authenticatable, :registerable,
  ##       :recoverable, :rememberable, :trackable, :validatable
    validates :matricula, uniqueness: true


  ##has_one :docente

end

projetoRails/cicmonit/app/controllers/professors_controller.rb
class ProfessorsController < ApplicationController
  before_action :set_professor, only: [:show, :edit, :update, :destroy]

  # GET /professors
  # GET /professors.json
  def index
    @professors = Professor.all
  end

  # GET /professors/1
  # GET /professors/1.json
  def show
  end

  # GET /professors/new
  def new
    @professor = Professor.new
  end

  # GET /professors/1/edit
  def edit
  end

  # POST /professors
  # POST /professors.json
  def create
    @professor = Professor.new(professor_params)

    respond_to do |format|
      if @professor.save
        format.html { redirect_to @professor, notice: 'Sucesso no cadastro do dicente #{@professor.nome}.' }
        format.json { render :show, status: :created, location: @professor }
      else
        format.html { render :new }
        format.json { render json: @professor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /professors/1
  # PATCH/PUT /professors/1.json
  def update
    respond_to do |format|
      if @professor.update(professor_params)
        format.html { redirect_to @professor, notice: 'Professor foi atualizado.' }
        format.json { render :show, status: :ok, location: @professor }
      else
        format.html { render :edit }
        format.json { render json: @professor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /professors/1
  # DELETE /professors/1.json
  def destroy
    @professor.destroy
    respond_to do |format|
      format.html { redirect_to professors_url, notice: 'Professor foi excluido' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_professor
      @professor = Professor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def professor_params
      params.require(:professor).permit(:nome, :matricula,:email,:encrypted_password)
    end
end

projetoRails/cicmonit/app/helpers/professors_helper.rb
module ProfessorsHelper
end

projetoRails/cicmonit/app/views/professors/_form.html.erb
<%= form_for(@professor) do |f| %>
  <% if @professor.errors.any? %>
    <div id="error_explanation">
      <%= pluralize(@professor.errors.count, "erro(s)") %> encontrado(s):
      <ul>
      <% @professor.errors.full_messages.each do |message| %>
        <%= message %>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="login">
    <div class="container">
      <div class="form">

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :matricula %><br>
    <%= f.text_field :matricula %>
  </div>
   <div class="field">
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </div>
   <div class="field">
    <%= f.label  :senha%><br>
    <%= f.password_field :senha %>
  </div>
  <div class="actions">
    <%= f.submit "Criar novo professor", class: "btn-submit"%>
  </div>
  </div>
  </div>
  </div>
<% end %>

projetoRails/cicmonit/app/views/professors/edit.html.erb
<h1>Editar Professor</h1>

<%= render 'form' %>

<%= link_to image_tag("show.png"), @professor %> |
<%= link_to image_tag("back.png"), professors_path %>

projetoRails/cicmonit/app/views/professors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listar Professores</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Matricula</th>
      <th>Email</th>
      <th colspan="3" hidden="hidden"></th>
    </tr>
  </thead>

  <tbody>
    <% @professors.each do |professor| %>
      <tr>
        <td><%= professor.nome %></td>
        <td><%= professor.matricula %></td>
        <td><%= professor.email %></td>
        <td><%= link_to image_tag("show.png"), professor %></td>
        <td><%= link_to image_tag("edit.png"), edit_professor_path(professor) %></td>
      <td><%= link_to image_tag("delete.png"), professor, method: :delete, data: { confirm: "Você tem certeza que deseja excluir o docente #{professor.nome}?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to image_tag("new.png"), new_professor_path %>

<!Inicio da tabela com todos os alunos de todas as turmas e disciplinas>
<table>
<tr>
  <th align="center">Aluno</th>
  <th align="center">Avaliação</th>
  <th align="center">Disciplina</th>
  <th align="center">Menção na Disciplina</th>
  <th align="center">Turma</th>

</tr>
<%@aluno =  Aluno.all%>
<% @aluno.each do|aluno| %>

    <% candidato = aluno.candidatos %>
    <% candidato.each do|candidato| %>

        <% turma = candidato.turmas %>
        <% turma.each do|turma| %>

        <% disciplina = Disciplina.find(turma.disciplina_id)%>

                <tr>
                  <td align="center"><%=link_to aluno.nome, edit_candidato_path(candidato) %></td>
                  <% if candidato.avaliacao == 0%>
                  <td align="center"><%= "INDEFERIDA"%></td>
                  <% elsif candidato.avaliacao == 1%>
                  <td align="center"><%= "VOLUNTARIO"%></td>
                  <% elsif candidato.avaliacao == 2%>
                  <td align="center"><%= "REMUNERADO"%></td>
                  <%else%>
                  <td align="center"><%= "AMBAS"%></td>
                  <%end%>
                  <td align="center"><%= disciplina.nome %></td>
                  <td align="center"><%= candidato.mencao %></td>
                  <td align="center"><%= turma.nome %></td>

                  <td><%= link_to image_tag("delete.png"), candidato, method: :delete, data: { confirm: "Você tem certeza que deseja excluir sua candidatura na turma #{turma.nome} de #{disciplina.nome}" } %></td>

                </tr>

        <% end %>
    <% end %>
<% end %>
</table>
</body>
<!Fim da tabela com todos os alunos de todas as turmas e disciplinas>

projetoRails/cicmonit/app/views/professors/new.html.erb
<h1>Novo Docente</h1>

<%= render 'form' %>

<%= link_to image_tag("back.png"), professors_path%>

projetoRails/cicmonit/app/views/professors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @professor.nome %>
</p>
<p>
  <strong>Matricula:</strong>
  <%= @professor.matricula %>
</p>
<p>
  <strong>Email:</strong>
  <%= @professor.email %>
</p>
<%= link_to image_tag("edit.png"), edit_professor_path(@professor) %> |
<%= link_to image_tag("back.png"), professors_path %>