projetoRails/cicmonit/config/routes.rb
Rails.application.routes.draw do

  resources :candidatos
  devise_for :users
  get 'sessions/new'

  get 'info_page/index'

  get 'docentes/index'

  get 'docentes/listar'

  get 'docentes/listarPorIRA'

  get 'docentes/listarTurmas'

  get 'docentes/show'

  get 'alunos/insere'

  get 'alunos/listar'

  resources :alunos

  resources :docentes
  devise_for :professors
  resources :professors

   unauthenticated do
       root :to =>"alunos#FrontPage", as: :unauthenticated_root
   end

  get 'disciplinas/showCampus'

  get 'disciplinas/showDepartamentos'

  get 'disciplinas/showDisciplinas'

  get 'disciplinas/showTurmas'

  get 'disciplinas/showTurma'

  get 'disciplinas/showHorarios'

  get 'disciplinas/showProfessores'

    get 'disciplinas/showCandidatos'

	resources:disciplina
  get 'configuracoes/index'
  get 'configuracoes/rungetdb'
  get 'configuracoes/runalocabolsas'
  get 'configuracoes/setbolsas'

  root 'alunos#FrontPage'

end

projetoRails/cicmonit/app/models/aluno.rb
class Aluno < ActiveRecord::Base
  validates :nome, length: {minimum:5, maximum: 255 }
  validates :nome, presence: true
  validates :matricula, presence: true
  validates :IRA, presence: true
  validates :semestre, inclusion: { in: 1..10 }
  validates :semestre, presence: true
  validates :user_id, presence: true
  validates :matricula, uniqueness: true


  has_many :candidatos

  belongs_to :user

end

projetoRails/cicmonit/app/models/campu.rb
class Campu < ActiveRecord::Base
  has_many :departamentos
end

projetoRails/cicmonit/app/models/candidato.rb
class Candidato < ActiveRecord::Base
  belongs_to :aluno
  # has_many :turmas, :through=>:turma_has_candidatos
  # has_many :turma_has_candidatos
  has_and_belongs_to_many :turmas
end

projetoRails/cicmonit/app/models/configuracoe.rb
class Configuracoe < ActiveRecord::Base

  self.table_name = "total_de_bolsas"

end

projetoRails/cicmonit/app/models/departamento.rb
class Departamento < ActiveRecord::Base
  belongs_to :campu
  has_many :disciplinas
end

projetoRails/cicmonit/app/models/disciplina.rb
class Disciplina < ActiveRecord::Base
  belongs_to :departamento
  has_many :turmas
end

projetoRails/cicmonit/app/models/docente.rb
class Docente < ActiveRecord::Base
  validates :nome, length: {maximum: 255 }
  validates :nome, presence: true

  belongs_to :user
  has_and_belongs_to_many :turmas
end

projetoRails/cicmonit/app/models/horario.rb
class Horario < ActiveRecord::Base
  belongs_to :turma
end

projetoRails/cicmonit/app/models/professor.rb
class Professor < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  ##devise :database_authenticatable, :registerable,
  ##       :recoverable, :rememberable, :trackable, :validatable
    validates :matricula, uniqueness: true


  ##has_one :docente

end

projetoRails/cicmonit/app/models/turma.rb
class Turma < ActiveRecord::Base
  belongs_to :disciplina
  has_many :horarios
  
  has_and_belongs_to_many :docentes

  has_and_belongs_to_many :candidatos
end

projetoRails/cicmonit/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

         has_many :alunos

         has_many :docentes

        VALID_EMAIL_FORMAT= /\A(?:[-0-9]+)@((?:[-a-u]+\.)+[a-z]{2,})\Z/i
        validates :email,  length: {maximum: 260}, uniqueness: {case_sensitive: false}

end

projetoRails/cicmonit/app/helpers/alunos_helper.rb
module AlunosHelper
  def formata_matricula(n_matricula)
    mat_formatada = ""
    mat_formatada << n_matricula[0..1]
    mat_formatada << "/"
    mat_formatada << n_matricula[2..8]
  end

  def formata_semestre(n_semestre)
    sem_formatado = "#{n_semestre}"
    sem_formatado << "º"
  end

end

projetoRails/cicmonit/app/helpers/application_helper.rb
module ApplicationHelper
end

projetoRails/cicmonit/app/helpers/candidatos_helper.rb
module CandidatosHelper
end

projetoRails/cicmonit/app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved',
      count: resource.errors.count,
      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alerta alerta-error">
      <a href="#" class="close" data-dismiss="alert">×</a>
      <strong> #{sentence}</strong >
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

projetoRails/cicmonit/app/helpers/disciplinas_helper.rb
module DisciplinasHelper
end

projetoRails/cicmonit/app/helpers/docentes_helper.rb
module DocentesHelper
end

projetoRails/cicmonit/app/helpers/info_page_helper.rb
module InfoPageHelper
end

projetoRails/cicmonit/app/helpers/professors_helper.rb
module ProfessorsHelper
end

projetoRails/cicmonit/app/helpers/sessions_helper.rb
module SessionsHelper

   def formata_email(email)
   	tamanho_matricula = 8#indices vao de 0 a size -1
   	if email.length < 13 then # basicamente serve para ver se o campo de email esta vazio. 
   		#Se estiver, vai preencher com @aluno.unb.br
    	#email_formatado = "#{email}" #campo de matricula que o usario esta preechendo

    	email_formatado = "@aluno.unb.br" #endereco de email que vem automaticamente logo depois do campo de matricula
  	elsif email.index("@")== nil # se nao tiver @
  		email_formatado = "@aluno.unb.br" #endereco de email que vem automaticamente logo depois do campo de matricula
  	elsif email[email.index("@")..email.length] != "@aluno.unb.br" # verifica se o dominio eh @aluno.unb.br
  	#codigo acima pega os indices de email(string) desde o indice do '@' ate o tamanho maximo da palavra 
  		if email.index("@")-1 <= tamanho_matricula then # se o campo de matricula digitado tem tamanho menor
  			#ou igual ao tamanho da matricula entao pegamos tudo antes do @. Sena pegamos os 9 primeiros caracteres
	  		email_formatado = email[0..(email.index("@")-1)] + "@aluno.unb.br" # pega tudo que o usuario digitou
	  		# ate o primeiro @ e concatena o resultado com "@aluno.unb.br"
  		else
  			email_formatado = email[0..8] + "@aluno.unb.br"
  		end 
  	else # email  tem o dominio da unb
  		if email.index("@")-1 <= tamanho_matricula then # se o campo de matricula digitado tem tamanho menor
  			#ou igual ao tamanho da matricula entao pegamos tudo antes do @. Sena pegamos os 9 primeiros caracteres
	  		email_formatado = email[0..(email.index("@")-1)] + "@aluno.unb.br" # pega tudo que o usuario digitou
	  		# ate o primeiro @ e concatena o resultado com "@aluno.unb.br"
  		else
  			email_formatado = email[0..8] + "@aluno.unb.br"
  		end 
  	end 
  end
end

projetoRails/cicmonit/app/views/layouts/_header.html.erb
<header>
	<nav>
      <ul class="nav-bar">
				<%if user_signed_in?%>
					<li><%=link_to "Campus",disciplinas_showCampus_path %></li>



					<% se1 = User.where("email = ? and id = ?",'unbmonitoria@gmail.com', current_user.id).count %>

					<% if se1 == 1 %>
						<li><%=link_to "Configurações", controller: "configuracoes", action: "index"%></li>

					<%else %>
								<% se = User.where("email like ? and id = ?",'%@aluno.unb.br', current_user.id).count %>

								<% if se == 1 %>
								<li><%= link_to "Perfil", alunos_path %></li>
								<li><%=link_to "Lista", controller: "alunos", action: "listar"%></li>
								<%else %>
								<li><%= link_to "Perfil", docentes_path %></li>
								<li><%=link_to "Lista", controller: "docentes", action: "listarTurmas"%></li>
								<% end %>
					<% end %>

					<li><%= link_to "Informações", info_page_index_path %></li>
			 		<li><%=link_to "Sair", destroy_user_session_path, method: "delete" %> </li>
			  <%else%>
					<li><%=link_to "Pagina Inicial",root_path %></li>
					<li><%= link_to "Informações", info_page_index_path %></li>

					<li><%= link_to 'Entrar', new_user_session_path, method: :get %></li>

			<%end%>



      </ul>
  </nav>
</header>

projetoRails/cicmonit/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Monitoria CIC</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= favicon_link_tag 'icone.ico' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script>
$(document).ready(function() {
setTimeout("$('#alertasenoticias').hide()", 2000);
});
</script>
</head>
<body>
  <div class="header">
    <%= link_to root_path do %>
      <img src="http://www.cic.unb.br/wp-content/uploads/2016/03/logo2.png" alt="Departamento de Ciência da Computação" align="right">
    <% end %>
      <div class="container">
        <div class="nav pull-right">
          <%= render 'layouts/header' %>
	</div>
      </div>
    </div>
    <div id="alertasenoticias">
      <p class="notice"> <%= notice %></p>
      <p class="alert"> <%= alert %></p>
    </div>
<%= yield %>

</body>
</html>